env:
  browser: true
  es6: true
  jquery: true
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2020
  sourceType: "module"
extends:
  - "plugin:@typescript-eslint/recommended"
  - "prettier/@typescript-eslint"
  - "plugin:prettier/recommended"
rules: {}
# extends:
#   - standard
#   - "plugin:prettier/recommended"
#   - "plugin:@typescript-eslint/eslint-recommended"
#   - "plugin:@typescript-eslint/recommended"
# globals:
#   Atomics: readonly
#   SharedArrayBuffer: readonly
# plugins:
#   - "@typescript-eslint"
#   - prettier
# rules:
#   quotes: ["error", "double", { "avoidEscape": true }]
#   semi: ["error", "always"]
#   space-before-function-paren: ["error", "never"]
#   # "prettier/prettier": ["error"]
