env:
  browser: true
  es6: true
  jquery: true
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2020
  sourceType: "module"
extends:
  - standard
  - "plugin:@typescript-eslint/recommended"
  - "prettier"
rules: {}
