name: PHP CI

on:
  push:
    paths:
      - ".github/workflows/php-ci.yml"
      - "composer.json"
      - "composer.lock"
      - "bin/**"
      - "config/**"
      - "src/**"
      - "test/**"
      - "**.php"
  pull_request:
    paths:
      - ".github/workflows/php-ci.yml"
      - "composer.json"
      - "composer.lock"
      - "bin/**"
      - "config/**"
      - "src/**"
      - "test/**"
      - "**.php"

jobs:
  check-test-php:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ["7.4"]
    steps:
      - uses: actions/checkout@v2
      - name: Use PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: curl
      - name: Validate composer.json and composer.lock
        run: composer validate
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
      - name: Configure PHPCS
        run: ./vendor/squizlabs/php_codesniffer/bin/phpcs --config-set ignore_warnings_on_exit 1
      - name: Run check suite
        run: composer run-script check
      - name: Run test suite
        run: composer run-script test
