name: PHP Composer

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ["7.4"]

    steps:
      - uses: actions/checkout@v2
      - name: Use PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: curl
          tools: phpcs, phpstan, phpunit
      - name: Validate composer.json and composer.lock
        run: composer validate
      - name: Install dependencies
        run: composer install --no-dev --prefer-dist --no-progress --no-suggest
      - name: Configure PHPCS
        run: phpcs --config-set ignore_warnings_on_exit 1
      - name: Run check suite
        run: composer run-script check
      - name: Run test suite
        run: composer run-script test
